In [1]:
import numpy as np

-create
-basic operation
-math operation
-indexing and slicing
-boolean filter

In [3]:
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [4]:
a = np.array([1,2,3,4,5])
print(x)
print(x.shape)

[1 2 3 4 5]
(5,)


In [5]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [6]:
z= [0,1,2,3,4,5,6,7,8,9]
nz = np.array([z]*10)
print(nz)
print(nz.shape)

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
(10, 10)


-random
-arrange
-linspace

In [7]:
np.random.rand(3,3)

array([[0.06058922, 0.43122514, 0.14480748],
       [0.25522786, 0.59214205, 0.52165002],
       [0.00491958, 0.36260105, 0.10799505]])

In [9]:
r1= np.random.randint(-5,6,(5,5))
print(r1)

[[ 0 -2 -1  2  4]
 [ 0 -2  0 -5 -1]
 [-1  3  5  2  1]
 [-3  0 -2 -1  2]
 [-1  3  3  3  5]]


In [11]:
np.arange(0,50, .5)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5,
       22. , 22.5, 23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. ,
       27.5, 28. , 28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5, 32. , 32.5,
       33. , 33.5, 34. , 34.5, 35. , 35.5, 36. , 36.5, 37. , 37.5, 38. ,
       38.5, 39. , 39.5, 40. , 40.5, 41. , 41.5, 42. , 42.5, 43. , 43.5,
       44. , 44.5, 45. , 45.5, 46. , 46.5, 47. , 47.5, 48. , 48.5, 49. ,
       49.5])

In [12]:
np.linspace(0,50,100)

array([ 0.        ,  0.50505051,  1.01010101,  1.51515152,  2.02020202,
        2.52525253,  3.03030303,  3.53535354,  4.04040404,  4.54545455,
        5.05050505,  5.55555556,  6.06060606,  6.56565657,  7.07070707,
        7.57575758,  8.08080808,  8.58585859,  9.09090909,  9.5959596 ,
       10.1010101 , 10.60606061, 11.11111111, 11.61616162, 12.12121212,
       12.62626263, 13.13131313, 13.63636364, 14.14141414, 14.64646465,
       15.15151515, 15.65656566, 16.16161616, 16.66666667, 17.17171717,
       17.67676768, 18.18181818, 18.68686869, 19.19191919, 19.6969697 ,
       20.2020202 , 20.70707071, 21.21212121, 21.71717172, 22.22222222,
       22.72727273, 23.23232323, 23.73737374, 24.24242424, 24.74747475,
       25.25252525, 25.75757576, 26.26262626, 26.76767677, 27.27272727,
       27.77777778, 28.28282828, 28.78787879, 29.29292929, 29.7979798 ,
       30.3030303 , 30.80808081, 31.31313131, 31.81818182, 32.32323232,
       32.82828283, 33.33333333, 33.83838384, 34.34343434, 34.84

-shape
-dtype
-ndim
-size

basic operations
-sum
-mean-min
-max
-std
-reshape
-transpose
-flatten

In [13]:
x.dtype

dtype('int64')

In [15]:
x=np.random.rand(3,3,)
x.dtype

dtype('float64')

In [16]:
x.ndim

2

In [19]:
z=np.random.randint(1,5, (3,3,3))
z.ndim

3

In [20]:
z.size

27

In [22]:
z.sum()

np.int64(60)

In [25]:
a = np.random.rand(2,3)
print(a.sum())
print(a.sum(axis=0))
print(a.sum(axis=1))
print(a.mean())
print(a.max())
print(a.min())
print(a.std())
print(a.var())

3.192502444990926
[0.41972586 1.35604327 1.41673331]
[1.42432673 1.76817571]
0.532083740831821
0.8500296311520973
0.11603720254784089
0.25107227470500537
0.06303728712554567


In [26]:
z= np.random.randint(11,99,(5,5))
print(z)
print('transpose')
print(z.transpose())
print('flattened')
print(z.flatten())




[[37 44 58 28 52]
 [16 16 51 49 63]
 [90 70 12 81 83]
 [85 28 90 33 38]
 [45 90 11 26 88]]
transpose
[[37 16 90 85 45]
 [44 16 70 28 90]
 [58 51 12 90 11]
 [28 49 81 33 26]
 [52 63 83 38 88]]
flattened
[37 44 58 28 52 16 16 51 49 63 90 70 12 81 83 85 28 90 33 38 45 90 11 26
 88]


In [31]:
a = np.random.randint(1,10, (4,5))
print(a)
print(a.reshape(20))
print(a.reshape(5,4))
print(a.reshape(2,10))
print(a.reshape(10,2))



[[6 3 4 7 5]
 [6 8 5 9 7]
 [6 4 2 2 8]
 [1 9 2 4 7]]
[6 3 4 7 5 6 8 5 9 7 6 4 2 2 8 1 9 2 4 7]
[[6 3 4 7]
 [5 6 8 5]
 [9 7 6 4]
 [2 2 8 1]
 [9 2 4 7]]
[[6 3 4 7 5 6 8 5 9 7]
 [6 4 2 2 8 1 9 2 4 7]]
[[6 3]
 [4 7]
 [5 6]
 [8 5]
 [9 7]
 [6 4]
 [2 2]
 [8 1]
 [9 2]
 [4 7]]


In [32]:
a = np.array([[1,2],[3,4]])
b = np.array([[6,2],[6,3]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[6 2]
 [6 3]]


In [34]:
print(a+b)
print(a-b)
print(a/b)
print(a*b)
print(a@b)
print(a.dot(b))


[[7 4]
 [9 7]]
[[-5  0]
 [-3  1]]
[[0.16666667 1.        ]
 [0.5        1.33333333]]
[[ 6  4]
 [18 12]]
[[18  8]
 [42 18]]
[[18  8]
 [42 18]]


In [36]:
print(a+10)
print(a-10)
print(a/10)
print(a*10)


[[11 12]
 [13 14]]
[[-9 -8]
 [-7 -6]]
[[0.1 0.2]
 [0.3 0.4]]
[[10 20]
 [30 40]]


In [37]:
print(a[0,0])
print(a[-1,-1])

1
4


In [41]:
x =np.random.randint(1,10,(5,5)) #slicing
print(x)
print(x[:,0])
print(x[:,-1])
print(x[:,:3])
print(x[:,:-1])

[[2 2 8 8 9]
 [5 7 7 4 4]
 [6 6 3 8 4]
 [5 5 5 4 2]
 [2 1 8 6 6]]
[2 5 6 5 2]
[9 4 4 2 6]
[[2 2 8]
 [5 7 7]
 [6 6 3]
 [5 5 5]
 [2 1 8]]
[[2 2 8 8]
 [5 7 7 4]
 [6 6 3 8]
 [5 5 5 4]
 [2 1 8 6]]


In [42]:
print(x[1:-1,1:-1])

[[7 7 4]
 [6 3 8]
 [5 5 4]]
